In [46]:
import pandas as pd
import os

# Enregistrement dans un dataframe de la base de données
df = pd.read_csv("Missing_Migrants_Global_Figures_allData.csv")

In [47]:
def map_to_continent(region_string):
    if pd.isna(region_string):
        return 'Unknown'
    
    region_string = region_string.lower().replace('(p)', '').strip()
    
    # Mapping simplifié
    if 'africa' in region_string:
        return 'Africa'
    elif 'asia' in region_string:
        return 'Asia'
    elif 'europe' in region_string:
        return 'Europe'
    elif 'oceania' in region_string:
        return 'Oceania'
    elif 'mixed' in region_string or 'unknown' in region_string:
        return 'Unknown'
    else:
        return 'Unknown'  # Catch-all

# Application sur une colonne Pandas
df['Continent of Origin'] = df['Region of Origin'].apply(map_to_continent)

In [48]:
df

,Main ID,Incident ID,Incident Type,Region of Incident,Incident Date,Incident Year,Month,Number of Dead,Minimum Estimated Number of Missing,Total Number of Dead and Missing,...,Cause of Death,Country of Incident,Migration Route,Location of Incident,Coordinates,UNSD Geographical Grouping,Information Source,URL,Source Quality,Continent of Origin
0,2014.MMP00001,2014.MMP00001,Incident,North America,2014-01-06,2014.0,January,1.0,NaN,1,...,Mixed or unknown,United States of America,US-Mexico border crossing,Pima Country Office of the Medical Examiner ju...,"31.650259, -110.366453",Northern America,Pima County Office of the Medical Examiner (PC...,http://humaneborders.info/,5,Unknown
1,2014.MMP00002,2014.MMP00002,Incident,North America,2014-01-12,2014.0,January,1.0,NaN,1,...,Mixed or unknown,United States of America,US-Mexico border crossing,Pima Country Office of the Medical Examiner ju...,"31.59713, -111.73756",Northern America,Pima County Office of the Medical Examiner (PC...,NaN,5,Unknown
2,2014.MMP00003,2014.MMP00003,Incident,North America,2014-01-14,2014.0,January,1.0,NaN,1,...,Mixed or unknown,United States of America,US-Mexico border crossing,Pima Country Office of the Medical Examiner ju...,"31.94026, -113.01125",Northern America,Pima County Office of the Medical Examiner (PC...,NaN,5,Unknown
3,2014.MMP00004,2014.MMP00004,Incident,North America,2014-01-16,2014.0,January,1.0,NaN,1,...,Violence,United States of America,US-Mexico border crossing,"near Douglas, Arizona, USA","31.506777, -109.315632",Northern America,"Ministry of Foreign Affairs Mexico, Pima Count...",http://bit.ly/1qfIw00,5,Unknown
4,2014.MMP00005,2014.MMP00005,Incident,Europe,2014-01-16,2014.0,January,1.0,0.0,1,...,Harsh environmental conditions / lack of adequ...,Russian Federation,NaN,Border between Russia and Estonia,"59.1551, 28",Northern Europe,EUBusiness (Agence France-Presse),http://bit.ly/1rTFTjR,1,Africa
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19243,2025.MMP0222,2025.MMP0222,Incident,Central America,2025-04-11,2025.0,April,2.0,NaN,2,...,Mixed or unknown,Mexico,NaN,"Former migrant Camp in Calzada Vallejo, Alcald...","19.49719463, -99.15512473",Central America,"El Universal,Infobae,El Pais,Aristegui Noticia...",https://perma.cc/T972-2CBK,3,Unknown
19244,2025.MMP0223,2025.MMP0223,Incident,Caribbean,2025-04-14,2025.0,April,1.0,NaN,1,...,Accidental death,Dominican Republic,NaN,"Building in Alta Gracia, Santo Domingo, Domin...","18.47713548, -69.95911588",Caribbean,Infobae,https://perma.cc/5CSV-477Z,1,Unknown
19245,2025.MMP0224,2025.MMP0224,Incident,North America,2025-01-07,2025.0,January,2.0,NaN,2,...,Accidental death,United States of America,NaN,"Fort Lauderdale-Hollywood Airport, Broward Cou...","26.07460736, -80.15102217",Northern America,"Infobae, ABC News",https://perma.cc/868S-7UTP,3,Unknown
19246,2025.MMP0225,2025.MMP0225,Incident,Central America,2025-04-18,2025.0,April,1.0,NaN,1,...,Drowning,Mexico,US-Mexico border crossing,"Rio Bravo close to Ejido Madero del Rio,Jimene...","29.24923159, -100.8015028",Central America,"Zócalo, El Heraldo de Juarez,Tiempo, Radiza Di...",https://perma.cc/932Q-4ED2,3,Unknown
19247,2025.MMP0226,2025.MMP0226,Incident,Caribbean,2025-04-16,2025.0,April,1.0,NaN,1,...,Vehicle accident / death linked to hazardous t...,Dominican Republic,NaN,"On the carretera Manolo Tavárez, Cañongo, Domi...","19.62301367, -71.69198354",Caribbean,Diario Libre,https://perma.cc/Z84U-7U68,1,Unknown

In [49]:
# On ne conserve que les incidents qui se sont produits en Europe ou en Méditerranée
df_filtre = df[df['Region of Incident'].isin(['Europe', 'Mediterranean'])]

# On ne garde que les informations qui nous intéressent (on conserve notamment les chiffres des disparitions mais ceux des décès)
colonnes_selectionnees = [
   'Region of Incident',
    'Country of Incident',
    'Migration Route',
    'Incident Date',
    'Incident Year',
    'Month',
    'Minimum Estimated Number of Missing', 
    'Continent of Origin'
]
df_filtre = df_filtre[colonnes_selectionnees]

# On enregistre le fichier final
df_filtre.to_csv("MissingMigrants_Europe_Med.csv", index=False)

In [50]:
df_filtre

,Region of Incident,Country of Incident,Migration Route,Incident Date,Incident Year,Month,Minimum Estimated Number of Missing,Continent of Origin
4,Europe,Russian Federation,NaN,2014-01-16,2014.0,January,0.0,Africa
6,Mediterranean,Greece,Eastern Mediterranean,2014-01-19,2014.0,January,NaN,Unknown
14,Europe,France,English Channel to the UK,2014-01-30,2014.0,January,0.0,Asia
17,Mediterranean,Spain,Western Mediterranean,2014-02-06,2014.0,February,0.0,Unknown
21,Mediterranean,Italy,Central Mediterranean,2014-02-17,2014.0,February,0.0,Africa
...,...,...,...,...,...,...,...,...
19233,Mediterranean,Libya,Central Mediterranean,2025-04-14,2025.0,April,NaN,Unknown
19234,Mediterranean,Libya,Central Mediterranean,2025-04-17,2025.0,April,NaN,Unknown
19235,Mediterranean,Libya,Central Mediterranean,2025-04-16,2025.0,April,NaN,Asia
19236,Europe,United Kingdom of Great Britain and Northern I...,English Channel to the UK,2025-04-18,2025.0,April,NaN,Unknown
19239,Europe,Belarus,Belarus-EU border,2025-01-22,2025.0,January,NaN,Asia